// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Analyzer
{
    public enum ColOps : int
    {
        IO, // Input/Output
		RD, // Reduction
		SH, // Shadow renew
		RA // Remote Access
	}

	public partial class CommPopoverController : NSViewController
	{
		public CommPopoverController (IntPtr handle) : base (handle)
		{
		}

        public void Init(int statNum, int interNum)
        {
			Console.WriteLine("Going to Init CommPopover");
			var stat = ViewController.CompareList.At(statNum);
			var inter = stat.Info.inter[interNum];

			CommLabel.StringValue = inter.times.comm.ToString("F2");
            CommLevel.DoubleValue = 100;

			SynchLabel.StringValue = inter.times.synch.ToString("F2");
			SynchLevel.DoubleValue = inter.times.synch / inter.times.comm * 100;

			LoadImbLabel.StringValue = inter.times.load_imb.ToString("F2");
            LoadImbLevel.DoubleValue = inter.times.load_imb / inter.times.comm * 100;

			TimeVarLabel.StringValue = inter.times.time_var.ToString("F2");
            TimeVarLevel.DoubleValue = inter.times.time_var / inter.times.comm * 100;

			var maxColOp = Math.Max(inter.col_op[(int)ColOps.IO].comm, inter.col_op[(int)ColOps.RD].comm);
			maxColOp = Math.Max(maxColOp, inter.col_op[(int)ColOps.SH].comm);
			maxColOp = Math.Max(maxColOp, inter.col_op[(int)ColOps.RA].comm);

			Console.WriteLine(maxColOp + " - " + ColOpLabel + " - " + ColOpLevel + " - " + ColOpNameLabel);

			if (inter.col_op[(int)ColOps.IO].comm == maxColOp) { 
			    ColOpNameLabel.StringValue = "Ввод/вывод";
			    ColOpLabel.StringValue = inter.col_op[(int)ColOps.IO].comm.ToString("F2");
			    ColOpLevel.DoubleValue = inter.col_op[(int)ColOps.IO].comm / inter.times.comm * 100;
			} else if (inter.col_op[(int)ColOps.RD].comm == maxColOp)
			{
				ColOpNameLabel.StringValue = "Редукция";
				ColOpLabel.StringValue = inter.col_op[(int)ColOps.RD].comm.ToString("F2");
				ColOpLevel.DoubleValue = inter.col_op[(int)ColOps.RD].comm / inter.times.comm * 100;
			} else if (inter.col_op[(int)ColOps.SH].comm == maxColOp)
			{
				ColOpNameLabel.StringValue = "Теневые грани";
				ColOpLabel.StringValue = inter.col_op[(int)ColOps.SH].comm.ToString("F2");
				ColOpLevel.DoubleValue = inter.col_op[(int)ColOps.SH].comm / inter.times.comm * 100;
			} else
			{
				ColOpNameLabel.StringValue = "Удал. доступ";
				ColOpLabel.StringValue = inter.col_op[(int)ColOps.RA].comm.ToString("F2");
				ColOpLevel.DoubleValue = inter.col_op[(int)ColOps.RA].comm / inter.times.comm * 100;
			}

			//Console.WriteLine(""inter.col_op[2].comm;
			Console.WriteLine("Init CommPopover OK");
		}
	}
}
