// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using CoreGraphics;

namespace Analyzer
{
	public partial class IdlePopoverController : NSViewController, PlotPopoverInterface
	{
		public IdlePopoverController (IntPtr handle) : base (handle)
		{
		}

		public CGSize Init(int statNum, int interNum)
		{
			//Console.WriteLine("Going to Init IdlePopover");
			var stat = ViewController.CompareList.At(statNum);
			var inter = stat.Info.inter[interNum];

			IdleLabel.StringValue = inter.times.idle.ToString("F2");
			IdleLevel.DoubleValue = 100;

			LoadLabel.StringValue = inter.times.load_imb.ToString("F2");
			LoadLevel.DoubleValue = inter.times.load_imb / inter.times.idle * 100;
			LoadLabel.TextColor = (LoadLevel.DoubleValue >= 80) ? NSColor.White : NSColor.Black;

			VarLabel.StringValue = inter.times.time_var.ToString("F2");
			VarLevel.DoubleValue = inter.times.time_var / inter.times.idle * 100;
			VarLabel.TextColor = (VarLevel.DoubleValue >= 80) ? NSColor.White : NSColor.Black;

			return new CGSize(211, 172);
		}
	}
}
