// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;

namespace Analyzer
{

	public partial class IntervalCompareViewController : NSViewController
	{

        private double plotMaxTime;

		public IntervalCompareViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var DataSource = new IntervalOutlineDataSource();
            DataSource.Intervals.Add(ViewController.CompareList.List[0].Interval);
            IntervalTree.DataSource = DataSource;
            IntervalTree.Delegate = new IntervalCompareOutlineDelegate(IntervalTree, Plot);
            IntervalTree.ExpandItem(IntervalTree.ItemAtRow(0), true);
            IntervalTree.SelectRow(0, false);
            
            plotMaxTime = Plot.Model.GetAxis("Time").ActualMaximum;
            ((IntervalCompareOutlineDelegate)IntervalTree.Delegate).SetMaxTime(plotMaxTime);
        }

    }
}
