// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Analyzer
{
	public partial class IntervalCompareViewController : NSViewController
	{

		public IntervalCompareViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            HelloLabel.StringValue = "Hello!";
            Console.WriteLine("Count: " + ViewController.CompareList.List.Count);
        }
    }
}
