// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using CoreGraphics;

namespace Analyzer
{

	public partial class IntervalCompareViewController : NSViewController
	{

        private double plotMaxTime;

		public IntervalCompareViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            PlotMaker plotMaker = new PlotMaker(Plot);

            var DataSource = new IntervalOutlineDataSource();
            DataSource.Intervals.Add(ViewController.CompareList.List[0].Interval);
            IntervalTree.DataSource = DataSource;
            IntervalTree.Delegate = new IntervalCompareOutlineDelegate(IntervalTree, plotMaker);
            IntervalTree.ExpandItem(IntervalTree.ItemAtRow(0), true);
            IntervalTree.SelectRow(0, false);

            plotMaxTime = plotMaker.intervalModel.GetAxis("Time").ActualMaximum;
            ((IntervalCompareOutlineDelegate)IntervalTree.Delegate).SetMaxTime(plotMaxTime);
        }

    }
}
