// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;

namespace Analyzer
{

    public partial class PopoverController : NSViewController
    {

        public PopoverController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            Console.WriteLine("Loaded");
        }

    }
}
